### ISSUE TITLE
Ready status background color not applied

### ISSUE THREAD

**Issue by roydeanjr** [ryanmitchell/ti-ext-customerdisplay#1]
Oddly the background color selected for the Ready status is not being applied. Is it because my Ready status is not simply "Ready", but "Ready for pickup"?

**Comment by ryanmitchell** [comment]
You have to choose a colour in the settings for this one - you’ll see a settings link for it in the main settings page.

**Comment by roydeanjr** [comment]
Yes, I chose a color and it is not being used.

**Comment by ryanmitchell** [comment]
Send me the data column of "thoughtco_customerdisplay_settings" in ti_extension_settings table and I'll look into it.

**Comment by roydeanjr** [comment]
a:4:{s:11:"prep_status";s:2:"13";s:10:"prep_color";s:7:"#00C0EF";s:12:"ready_status";s:2:"20";s:11:"ready_color";s:7:"#4A00FF";}

**Comment by ryanmitchell** [comment]
Cheers - pushed a fix for it

**Comment by roydeanjr** [comment]
Got it! Thank you!
